### ISSUE TITLE
Unexpected "Core Error" and can't sign in

### ISSUE THREAD

**Issue by Blindsite** [maidsafe/beaker-plugin-safe-authenticator#146] opened 2017-09-23 20:43 UTC
Ok I keep getting this:

"Core error: Unexpected: Could not connect to the SAFE Network" When trying to create a new account on test net alpha 2 using the safe browser.   

I'm using Windows 7

**Comment by Sprkz** [comment] 2017-09-24 09:06
FIX for Registered IP : Not Set    seems when I request token for Alpha 2 it shows my 'Registered IP : Not Set'.  'Set IP' is greyed out so I get 'code error: could not connect to safe network' error.

To set your IP and resolve the issue I found that selecting Testnet 19 first thru the invitation where the Set IP is in blue and does work, then unblocks same button on Testnet Alpha 2 letting you set your IP and authenticate without error.

FYI

**Comment by bochaco** [comment] 2017-12-12 17:55
I'm closing this as the original error seems to be due to the IP not being set/whitelisted. Also, I cannot reproduce the issue when going to `https://invite.maidsafe.net`, I'm not sure if it's because there is no `Test-19` option now, in any case please please feel free to re-open it if you can reproduce it again.

**Closed by bochaco** 2017-12-12 17:55 UTC
